name: Update Wind Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download wind data (with retries)
        run: |
          for i in {1..5}; do
            echo "Attempt $i to download wind data..."
            curl -s -L "https://www.getnora.app/api/station/kite2fly-podersdorf?limit=30" -o wind.json && break
            sleep 2
          done

      - name: Validate JSON
        run: jq empty wind.json

      - name: Commit wind.json (always)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add wind.json
          git commit -m "Update wind data" || echo "No changes to commit"
          git push

  deploy:
    needs: update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Disable Jekyll
        run: echo "" > .nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Pages
        uses: actions/build-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
